### ISSUE TITLE
Cannot "connect" in OASEES portal

### ISSUE THREAD

**Issue by wtaverni** [oasees/oasees-stack-prototype#2]
I successfully installed the platform and get all 4 containers running after docker compose. I then created the metamask account according to the first video [here](https://nocncsrd.sharepoint.com/sites/OASEES2/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FOASEES2%2FShared%20Documents%2FWP4%2FMeetings%2FOASEES%20stack%20installation&p=true&ga=1), but I get an error when I then try to connect in the portal website (action at 2:45 in the first video).

1. Upon first try I got the following error:

Uncaught runtime errors:

> ×
> 
> ERROR
> 
> Cannot read properties of undefined (reading 'request') TypeError: Cannot read properties of undefined (reading 'request') at connectToMetaMask (http://localhost:3000/static/js/bundle.js:112:44) at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:12632:18) at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:12676:20) at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:12733:35) at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/bundle.js:12747:29) at executeDispatch (http://localhost:3000/static/js/bundle.js:16890:7) at processDispatchQueueItemsInOrder (http://localhost:3000/static/js/bundle.js:16916:11) at processDispatchQueue (http://localhost:3000/static/js/bundle.js:16927:9) at dispatchEventsForPlugins (http://localhost:3000/static/js/bundle.js:16936:7) at http://localhost:3000/static/js/bundle.js:17096:16

2. Upon second try (after reboot of machine), I got the following error:

> ERROR
> 
> Network Error AxiosError: Network Error at XMLHttpRequest.handleError (http://localhost:3000/static/js/bundle.js:53041:14)

My network connection is working fine. 

Any idea on how to resolve this?

Thanks!

Wouter

NOTE: I had to add the line "platform: linux/amd64" for the oasees_blockchain container in the docker-compose.yaml on M1 macbook.

**Comment by OikonomakisAndreas** [comment]
We have updated the portal (Maybe the connect button does some weird things when it is double clicked) In this version we disabled the button until the login procedure is completed.
-Make sure that you type your host's ip (not localhost) to the browser.
-Before re-installing run docker-compose down -v
-Clear the metamask activity and nonce data between fresh installations

**Comment by wtaverni** [comment]
After pulling the latest version, `docker-compose down -v`, running `docker compose up -d --build` and using IP address instead of localhost, I still get the error:

> Network Error
> AxiosError: Network Error
>     at XMLHttpRequest.handleError (http://192.168.50.91:3000/static/js/bundle.js:53043:14)
